DC-3443: auth client upgrade
hmrc/two-way-message pull request #146
Opened 2021-06-18 13:07 UTC by matthewgroom

2021-06-21 18:00 UTC, alexflav23 requested changes

2021-06-21 18:00 UTC, alexflav23 commented on app/uk/gov/hmrc/gform/gformbackend/GformConnector.scala
> +        case Right(httpResponse) => java.util.UUID.fromString(httpResponse.body)
What is this is not a valid UUID? We need to wrap this around a try or something don't we?

2021-06-22 07:28 UTC, matthewgroom commented on app/uk/gov/hmrc/gform/gformbackend/GformConnector.scala
> +        case Right(httpResponse) => java.util.UUID.fromString(httpResponse.body)
I believe it already deals with this when trying to create a UUID => throw new IllegalArgumentException("Invalid UUID string: "+name);

2021-06-22 07:56 UTC, spifix-hmrc commented on app/uk/gov/hmrc/gform/gformbackend/GformConnector.scala
> +        case Right(httpResponse) => java.util.UUID.fromString(httpResponse.body)
I guess the future will be failed in this case `ws.POST[DmsHtmlSubmission, java.util.UUID](s"$baseUrl/dms/submit", submission)` :)

2021-06-22 08:07 UTC, spifix-hmrc approved these changes

2021-06-22 12:25 UTC, merged